theme: jekyll-theme-hacker
title: Karsten Johansson's Raspberry Pi and Infosec Hacking Stuff
description: WIP so you are probably better off using my github repo for now... I'll be building this over the ~~next few days~~.
